### ISSUE TITLE
FT Client, Mysql and Emulator Server crash constantly

### ISSUE THREAD

**Issue by Ari089erz** [sstokic-tgm/JFTSE#180]
Hello everyone, 

after I created my first test character, the FT client hangs and I get kicked from the server, this happens again and again.
 The docker then restarts the emulator & mysql server.

I run the emulator, mysql and rabbitmq server via the docker.
Can anyone help me?

Best regards
Ari089erz

**Comment by Ari089erz** [comment]
![Image](https://github.com/user-attachments/assets/bb14f7ed-21a7-4927-a4e2-88bb113dc0b8)

**Comment by Ari089erz** [comment]
![Image](https://github.com/user-attachments/assets/093350bd-2c69-446b-a2c7-fff7171e423f)

I created the character using the database because somehow you can't create a character. However, you cannot log into a channel.

Can someone tell me why this is?

**Comment by GohanDS** [comment]
![Image](https://github.com/user-attachments/assets/19092e13-d7d1-4e55-a789-06f064c7593c)

![Image](https://github.com/user-attachments/assets/5f3235d6-5d84-4005-a3f9-a0a3b8904aef)

The same here. Please help.

**Comment by Ari089erz** [comment]
Hello, can anyone give us any info on whether the problem will be fixed?

**Comment by Ari089erz** [comment]
Hi, I did everything according to the instructions and I use the master version.
I run it all over the docker and somehow I always get this error with the mysql server.

**Comment by Ari089erz** [comment]
![Image](https://github.com/user-attachments/assets/f15abfc8-e265-4a55-b910-4e7ea8d14cc4)

**Comment by Ari089erz** [comment]
![Image](https://github.com/user-attachments/assets/34f177b7-a519-449b-833a-1430eb06989a)

![Image](https://github.com/user-attachments/assets/caafb4bc-ce7e-4e7b-b53d-c98e414ca664)

**Comment by Ari089erz** [comment]
![Image](https://github.com/user-attachments/assets/45fee1c3-d831-495a-9f3b-76634dd86cc5)

![Image](https://github.com/user-attachments/assets/b2e20e42-08f1-4523-b720-0c2a1e4b0f5d)

**Comment by Ari089erz** [comment]
Could I have your Discord please?

**Comment by Ari089erz** [comment]
![Image](https://github.com/user-attachments/assets/e0d42bd7-3b3b-40fa-a016-fe958f3f8432)

**Comment by sstokic-tgm** [comment]
Are you able to still connect to the db even thouh you see that message? (through some tool or CLI. atleast through screenshots I can see that the mysql.db works fine even though you see the warning)
You can add this line to the docker-compose.yml in the mysql-db service section:
```
cap_add:
  - SYS_NICE
```
Reference: https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log

Other than that, the GameServer table looks good, ServerInfo.txt I guess is also correct since you wouldn't be able to login. 
What might still be the issue, are some tables which have to be automatically populated by the auth-server. I am unsure now if, the master branch already has the new logic for importing or only the development branch but it can be that it's same in the master branch. Hence you need to run once (so its initialized):
`java -jar auth-server-1.0.0-SNAPSHOT.jar -import`

What you can do to do that is, to connect to the emulator docker container and run a few commands.
```
docker exec -it emulator bash
ps aux | grep java
kill <id of auth-server-1.0.0-SNAPSHOT.jar which you see with the ps aux command for it>
cd ~/
java -jar path/where/it/resides/on/docker/volume/auth-server-1.0.0-SNAPSHOT.jar -import
```
with ls and directory changes you can get to the correct folder.

You can also change this file: https://github.com/sstokic-tgm/JFTSE/blob/master/docker/emulator/supervisord.conf
In the auth-server section to include "-import" at the end of the command definition for it -> but that means it will run always the import of the static data into the db as soon as you start the docker so maybe for the one time init you can change it so you have it run once so your db is initialized and then you have it changed back to without the "-import" argument. Changing that file I think requires you to run docker build on emulator so the new config file is used by the container.

**Comment by Ari089erz** [comment]
![Image](https://github.com/user-attachments/assets/88961ac2-8e3a-4f24-847b-5c365b69f86e)

the problem persists even if I enter this line with cap_add there ...

**Comment by Ari089erz** [comment]
![Image](https://github.com/user-attachments/assets/77ee5198-099d-4f7d-86f1-2caac0a48fb7)

**Comment by Ari089erz** [comment]
I honestly don't know what to do anymore, I've tried everything possible

**Comment by Ari089erz** [comment]
![Image](https://github.com/user-attachments/assets/b914f503-4b31-4597-b28e-e9fb8428b1ba)

Which TLS versions do I actually need?

**Comment by sstokic-tgm** [comment]
You didn't understand me correctly. TLS has nothing to do with it.
The lines added make the YML syntax wrong, ident wise. The final file should look like:
```
version: '3.8'

services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq-server
    hostname: rabbitmq-server
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-network

  mysql-db:
    build:
      context: ./mysql-db
      dockerfile: Dockerfile
    container_name: mysql-db-server
    hostname: mysql-db-server
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    networks:
      - db-network

  emulator:
    build:
      context: ..
      dockerfile: docker/emulator/Dockerfile
    container_name: emulator-server
    hostname: emulator-server
    depends_on:
      - "mysql-db"
      - "rabbitmq"
    ports:
      - "5894:5894"
      - "5895:5895"
      - "5896:5896"
      - "5897:5897"
      - "3724:3724"
    networks:
      - db-network
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge
    name: rabbitmq-network
  db-network:
    driver: bridge
    name: db-network
```

Next, the error you see there is no error but a warning, you can query your DB and see data, that means it's working. What is not working is what I described in my previous post, regarding importing data.
